from dotenv import load_dotenv
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_openai import ChatOpenAI

load_dotenv()


# Create the prompt template for reflection
# A reflection agent is an agent that can critique its own performance and make recommendations for improvement. In this case, we will create a reflection agent that can critique a tweet and make recommendations for how to make it go viral. The prompt template will include a system message that describes the role of the agent and a placeholder for the messages that will be generated by the agent. The system message will also include instructions for the agent to provide detailed recommendations, including requests for length, tone, and style of the tweet.

reflection_prompt = ChatPromptTemplate.from_messages(
    [
        ("system",
         "You are a viral twitter influencer grading a tweet. Generate critique and recommendations to make the tweet go viral. "
         "Always provide detailed recommendations, including request for length, tone, and style of the tweet."),
        MessagesPlaceholder(variable_name="messages"),
    ]
)

generation_prompt = ChatPromptTemplate.from_messages([
    ("system",
     "You are a twitter techie influencer assistant tasked with writing excellent twitter posts. "
     "Generate a tweet that is likely to go viral based on the critique and recommendations provided by the reflection agent. "
     "If the user provided critique, respond with a revised version of your previous attempts."),
    MessagesPlaceholder(variable_name="messages"),
])

llm = ChatOpenAI()
generate_chain = generation_prompt | llm
reflect_chain = reflection_prompt | llm 

